"""views field nullable

Revision ID: 0960a4f16c69
Revises: 05313fe81443
Create Date: 2021-02-04 16:16:28.770806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0960a4f16c69'
down_revision = '05313fe81443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_queue', schema=None) as batch_op:
        batch_op.alter_column('views',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_queue', schema=None) as batch_op:
        batch_op.alter_column('views',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
