"""service field

Revision ID: 200f1dd843f0
Revises: 0960a4f16c69
Create Date: 2021-07-01 13:54:43.621067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200f1dd843f0'
down_revision = '0960a4f16c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_queue', schema=None) as batch_op:
        batch_op.drop_column('service')

    # ### end Alembic commands ###
