"""add boolean field nullable

Revision ID: 27ba3757b219
Revises: e55e5faf7d1c
Create Date: 2021-07-15 14:28:55.235364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ba3757b219'
down_revision = 'e55e5faf7d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('sec_alg',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('sec_alg',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
