"""service field nullable

Revision ID: 4612686689ec
Revises: 200f1dd843f0
Create Date: 2021-07-01 13:58:31.479138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4612686689ec'
down_revision = '200f1dd843f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_queue', schema=None) as batch_op:
        batch_op.alter_column('service',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_queue', schema=None) as batch_op:
        batch_op.alter_column('service',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###
