"""new tables > drop columns

Revision ID: 52338873675f
Revises: 4ced4a69e358
Create Date: 2021-07-14 16:29:43.149627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52338873675f'
down_revision = '4ced4a69e358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_viewer', schema=None) as batch_op:
        batch_op.drop_column('prev_views')
        batch_op.drop_column('name')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=10), nullable=False))

    with op.batch_alter_table('current_viewer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('prev_views', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
