"""successfull field

Revision ID: 72a7248e4c59
Revises: cff7c547b6c4
Create Date: 2021-07-22 11:20:49.986831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a7248e4c59'
down_revision = 'cff7c547b6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('browsing_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_successful', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('browsing_history', schema=None) as batch_op:
        batch_op.drop_column('is_successful')

    # ### end Alembic commands ###
