"""new tables > Settings, CurrentViewer

Revision ID: ade6016058f6
Revises: 4612686689ec
Create Date: 2021-07-14 15:05:50.740989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade6016058f6'
down_revision = '4612686689ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_viewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prev_views', sa.Integer(), nullable=False),
    sa.Column('curr_views', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thr_num', sa.Integer(), nullable=False),
    sa.Column('sec_alg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('current_viewer')
    # ### end Alembic commands ###
