"""new field - CV nullable

Revision ID: cff7c547b6c4
Revises: e1e9c2604a6b
Create Date: 2021-07-15 15:43:12.470667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff7c547b6c4'
down_revision = 'e1e9c2604a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_viewer', schema=None) as batch_op:
        batch_op.alter_column('need_views',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_viewer', schema=None) as batch_op:
        batch_op.alter_column('need_views',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
