"""new tables > add columns

Revision ID: d2ee4bb95abe
Revises: ade6016058f6
Create Date: 2021-07-14 15:21:34.850612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ee4bb95abe'
down_revision = 'ade6016058f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_viewer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=10), nullable=True))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('current_viewer', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
