"""new field - CV

Revision ID: e1e9c2604a6b
Revises: 27ba3757b219
Create Date: 2021-07-15 15:42:07.977648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e9c2604a6b'
down_revision = '27ba3757b219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_viewer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('need_views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_viewer', schema=None) as batch_op:
        batch_op.drop_column('need_views')

    # ### end Alembic commands ###
